src/main/java/com/networking/dto/MessageDTO.java
package com.networking.dto;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.Table;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;

@Entity
@Table(name = "messages")

@NamedNativeQueries({
        @NamedNativeQuery(
                name = "deleteMessageById",
                query = "delete " +
                        "FROM messages where id = :id"
        ),
        @NamedNativeQuery(
                name = "findMessagesByChat",
                query = "select * " +
                        "FROM messages where chat_id = :chat_id order by created_date desc",
                resultClass = MessageDTO.class
        ),
        @NamedNativeQuery(
                name = "createMessageManually",
                query = " insert into  " +
                        " messages (chat_id, created_by, created_date, message) " +
                        " values " +
                        " (:chatId, :createdBy, :createdDate, :message)"
        )
})
public class MessageDTO {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "chat_id", nullable = false)
    private ChatDTO chat;

    @Column(name = "created_date")
    private Date createdDate;

    @ManyToOne(cascade = CascadeType.ALL, targetEntity = UserDTO.class, fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    private UserDTO createdBy;

    private String message;

    public Integer getId() {
        return id;
    }

    public MessageDTO setId(Integer id) {
        this.id = id;
        return this;
    }

    public ChatDTO getChat() {
        return chat;
    }

    public MessageDTO setChat(ChatDTO chat) {
        this.chat = chat;
        return this;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public MessageDTO setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    public UserDTO getCreatedBy() {
        return createdBy;
    }

    public MessageDTO setCreatedBy(UserDTO createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    public String getMessage() {
        return message;
    }

    public MessageDTO setMessage(String message) {
        this.message = message;
        return this;
    }

    public String getDateFormatted() {
        return new SimpleDateFormat("dd/MM/yyyy hh:mm").format(this.createdDate);
    }

}

src/main/java/com/networking/action/FriendsAction.java
package com.networking.action;

import com.networking.dto.UserDTO;
import com.networking.service.FriendService;
import com.networking.service.UserService;
import com.opensymphony.xwork2.ActionSupport;
import org.apache.struts2.dispatcher.SessionMap;
import org.apache.struts2.interceptor.SessionAware;

import java.util.List;
import java.util.Map;

public class FriendsAction extends ActionSupport implements SessionAware {

    public static final String SESSION_ATTRIBUTE_USER = "user";

    private UserService userService = UserService.getInstance();
    private FriendService friendService = FriendService.getInstance();

    private UserDTO user;
    private Integer friendId;

    private UserDTO friend;
    private String friendName;

    private List<UserDTO> friends;

    private List<UserDTO> availableusers;

    private String newFriendUserName;

    private SessionMap<String, Object> sessionmap;

    @Override
    public void setSession(Map<String, Object> map) {
        sessionmap = (SessionMap) map;
    }

    public String show() {
        user = (UserDTO) sessionmap.get(SESSION_ATTRIBUTE_USER);
        friends = friendService.getFriends(user.getId());
        return "SUCCESS";
    }

    public String find() {
        user = (UserDTO) sessionmap.get(SESSION_ATTRIBUTE_USER);
        availableusers = userService.getAvailableUsers(user.getId());
        return "SUCCESS";
    }

    public void follow() {
        user = (UserDTO) sessionmap.get(SESSION_ATTRIBUTE_USER);
        friendService.follow(user.getId(), friendId);
    }

    public void unfollow() {
        user = (UserDTO) sessionmap.get(SESSION_ATTRIBUTE_USER);
        friendService.unfollow(user.getId(), friendId);
    }

    public String gotoFriend() {
        friend = userService.getUser(friendId);
        return friend != null ? "SUCCESS" : "FAILURE";
    }

    public UserDTO getUser() {
        return user;
    }

    public FriendsAction setUser(UserDTO user) {
        this.user = user;
        return this;
    }

    public List<UserDTO> getAvailableusers() {
        return availableusers;
    }

    public FriendsAction setAvailableusers(List<UserDTO> availableusers) {
        this.availableusers = availableusers;
        return this;
    }

    public UserDTO getFriend() {
        return friend;
    }

    public FriendsAction setFriend(UserDTO friend) {
        this.friend = friend;
        return this;
    }

    public String getFriendName() {
        return friendName;
    }

    public FriendsAction setFriendName(String friendName) {
        this.friendName = friendName;
        return this;
    }

    public String getNewFriendUserName() {
        return newFriendUserName;
    }

    public FriendsAction setNewFriendUserName(String newFriendUserName) {
        this.newFriendUserName = newFriendUserName;
        return this;
    }

    public List<UserDTO> getFriends() {
        return friends;
    }

    public FriendsAction setFriends(List<UserDTO> friends) {
        this.friends = friends;
        return this;
    }

    public Integer getFriendId() {
        return friendId;
    }

    public FriendsAction setFriendId(Integer friendId) {
        this.friendId = friendId;
        return this;
    }
}

src/main/java/com/networking/action/MessagesAction.java
package com.networking.action;

import com.networking.dto.ChatDTO;
import com.networking.dto.FriendDTO;
import com.networking.dto.MessageDTO;
import com.networking.dto.UserDTO;
import com.networking.service.ChatService;
import com.networking.service.FriendService;
import com.networking.service.MessageService;
import com.opensymphony.xwork2.ActionSupport;
import org.apache.struts2.interceptor.SessionAware;

import java.util.List;
import java.util.Map;

public class MessagesAction extends ActionSupport implements SessionAware {

    private MessageService messageService = MessageService.getInstance();
    private FriendService friendService = FriendService.getInstance();
    private ChatService chatService = ChatService.getInstance();

    private Map<String, Object> sessionMap;

    private List<MessageDTO> messages;

    private List<FriendDTO> chats;

    private ChatDTO chat;

    private Integer friendId;

    private Integer messageId;

    private Integer chatId;

    private String message;

    private MessageDTO messageObj;

    @Override
    public void setSession(Map<String, Object> map) {
        sessionMap = map;
    }

    public String loadWholeChat() {
        UserDTO user = (UserDTO) sessionMap.get("user");
        chat = chatService.find(user.getId(), friendId);
        messages = messageService.loadWholeChat(chat.getId());
        return "SUCCESS";
    }

    public String loadFriends() {
        UserDTO user = (UserDTO) sessionMap.get("user");
        chats = friendService.getFriendships(user.getId());
        return "SUCCESS";
    }

    public String create() {
        UserDTO user = (UserDTO) sessionMap.get("user");
        messageObj = messageService.createMessage(chatId, user, message);
        return "SUCCESS";
    }

    public String delete() {
        messageService.deleteMessage(messageId);
        return "SUCCESS";
    }

    public Integer getMessageId() {
        return messageId;
    }

    public MessagesAction setMessageId(Integer messageId) {
        this.messageId = messageId;
        return this;
    }

    public Integer getChatId() {
        return chatId;
    }

    public MessagesAction setChatId(Integer chatId) {
        this.chatId = chatId;
        return this;
    }

    public String getMessage() {
        return message;
    }

    public MessagesAction setMessage(String message) {
        this.message = message;
        return this;
    }

    public MessageDTO getMessageObj() {
        return messageObj;
    }

    public MessagesAction setMessageObj(MessageDTO messageObj) {
        this.messageObj = messageObj;
        return this;
    }

    public List<MessageDTO> getMessages() {
        return messages;
    }

    public MessagesAction setMessages(List<MessageDTO> messages) {
        this.messages = messages;
        return this;
    }

    public List<FriendDTO> getChats() {
        return chats;
    }

    public MessagesAction setChats(List<FriendDTO> chats) {
        this.chats = chats;
        return this;
    }

    public Integer getFriendId() {
        return friendId;
    }

    public MessagesAction setFriendId(Integer friendId) {
        this.friendId = friendId;
        return this;
    }

    public ChatDTO getChat() {
        return chat;
    }

    public MessagesAction setChat(ChatDTO chat) {
        this.chat = chat;
        return this;
    }
}

src/main/java/com/networking/action/PostsAction.java
package com.networking.action;

import com.networking.dto.PostDTO;
import com.networking.dto.UserDTO;
import com.networking.service.PostService;
import com.opensymphony.xwork2.ActionSupport;
import org.apache.struts2.dispatcher.SessionMap;
import org.apache.struts2.interceptor.SessionAware;

import java.util.Map;

public class PostsAction extends ActionSupport implements SessionAware {

    private Integer wallId;
    private Integer userId;
    private String content;

    private Integer postId;

    private PostDTO post;

    private PostService postService = PostService.getInstance();

    private SessionMap<String, Object> sessionmap;

    @Override
    public void setSession(Map<String, Object> map) {
        sessionmap = (SessionMap) map;
    }

    public String create() {
        UserDTO user = (UserDTO) sessionmap.get("user");
        post = postService.createNewPost(wallId, user.getId(), content);
        return "SUCCESS";
    }

    public void delete() {
        postService.deletePost(postId);
    }

    public PostDTO getPost() {
        return post;
    }

    public PostsAction setPost(PostDTO post) {
        this.post = post;
        return this;
    }

    public Integer getWallId() {
        return wallId;
    }

    public PostsAction setWallId(Integer wallId) {
        this.wallId = wallId;
        return this;
    }

    public Integer getUserId() {
        return userId;
    }

    public PostsAction setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    public String getContent() {
        return content;
    }

    public PostsAction setContent(String content) {
        this.content = content;
        return this;
    }

    public Integer getPostId() {
        return postId;
    }

    public PostsAction setPostId(Integer postId) {
        this.postId = postId;
        return this;
    }
}

src/main/webapp/WEB-INF/jsp/partitions/availablefriends.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<script>
    function follow(userId) {

           var datastring = "friendId=" + userId;
           $.ajax({
               type: "POST",
               url: "follow.action",
               data: datastring,
               success: function() {
                   $("#avail" + userId).remove();
               },
               error: function() {
                   alert('error handling here');
               }
           });
    }
</script>
<div class="friends">
    <s:iterator var="friend" value="availableusers">
        <div class="avail panel" id="avail${friend.id}">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-sm-10">
                    <a href="gotofriend.action?friendId=${friend.id}">${friend.username}</a>
                    </div>
                    <div class="col-sm-2">
                        <input type="button" onclick="follow(${friend.id})" class="btn btn-sm btn-default" value="Follow"/>
                    </div>
                </div>
            </div>
        </div>
    </s:iterator>
</div>

src/main/webapp/WEB-INF/jsp/partitions/chat.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<div class="chat panel">
    <div class="panel-heading">
        <div class="row">
            <div class="col-sm-12">
                <a href="chat.action?friendId=${chat.friend.id}"><s:property value="#chat.friend.username"/></a>
            </div>
        </div>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/partitions/chatopen.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>

<div class="friend">
    <s:hidden class="friendship" value="%{friendship.id}"/>
    <a href="chat.action?friendship=${friendship.id}"><s:property value="#friend.username"/></a>
    <div>
        <button onclick="unfollow($(this).closest('.friend'))">Delete</button>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/partitions/friends.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<div class="friends">
    <s:iterator var="friend" value="friends">
        <div class="friend panel">
            <input type="hidden" class="friendId" value="${friend.id}"/>
            <div class="panel-heading">
                <div class="row">
                    <div class="col-sm-10">
                    <a href="gotofriend.action?friendId=${friend.id}"><s:property value="#friend.username"/></a>
                    </div>
                    <div class="col-sm-2">
                        <button class="btn btn-sm btn-default" onclick="unfollow($(this).closest('.friend'))">Unfollow</button>
                    </div>
                </div>
            </div>
        </div>
    </s:iterator>
</div>

src/main/webapp/WEB-INF/jsp/partitions/message.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<div class="message panel blue ${user.id eq messageObj.createdBy.id ? 'rightblock' : 'leftblock grey'}">
    <s:hidden class="messageId" value="%{#messageObj.id}"/>
    <div class="header panel-heading">
        <div class="row">
            <span class="col-sm-3 col-sm-offset-8">
                ${messageObj.dateFormatted}
            </span><%--
            <div class="col-sm-1">
                <button class="btn btn-sm btn-default" style="padding-bottom: 1px; padding-top: 1px;" onclick="removeMessage($(this).closest('.message'))">x</button>
            </div>--%>
        </div>
    </div>
    <div class="content panel-body">
        <s:property value="#messageObj.message"/>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/partitions/newmessage.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<div class="newmessage row">
    <script>
        $(document).ready(function() {
            $("#newmessageform").submit(function(event) {
               event.preventDefault();
                var datastring = $(this).serialize();
                /*$.ajax({
                    type: "POST",
                    url: "newmessage.action",
                    data: datastring,
                    dataType: "html",
                    success: function(data) {
                        if ($(".messages .message").length == 0) {
                            $($(".messages")[0]).html(data);
                        } else {
                            $($(".messages .message")[0]).before(data);
                        }
                        $("#message").val("");
                    },
                    error: function() {
                        alert('error handling here');
                    }
                });*/
                chat.sendMessage($(this).find('#message').val());
            });
        });
    </script>
    <div class="jumbotron col-lg-12">
    <form id="newmessageform" action="newmessage.action" method="POST" style="display: block;">
        <input type="hidden" id="userId" name="userId" value="%{user.id}"/>
        <input type="hidden" id="chatId" name="chatId" value="%{chat.id}"/>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <textarea id="message" name="message" placeholder="Tell something..."  class="form-control"></textarea>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-12">
                    <div class="row">
                        <input type="submit" name="post-submit" id="post-submit" class="btn btn-sm btn-success col-sm-3 col-sm-offset-6" value="Send">
                        <input type="button" value="Clear" class="btn btn-sm col-sm-3" onclick="$('#newmessageform #message').val('');"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/partitions/newpost.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<div class="newpost row">
    <script>
        $(document).ready(function() {
            $("#newpostform").submit(function(event) {
               event.preventDefault();
                var datastring = $(this).serialize();
                $.ajax({
                    type: "POST",
                    url: "newpost.action",
                    data: datastring,
                    dataType: "html",
                    success: function(data) {
                        if ($(".posts .post").length == 0) {
                            $($(".posts")[0]).html(data);
                        } else {
                            $($(".posts .post")[0]).before(data);
                        }
                        $("#content").val("");
                    },
                    error: function() {
                        alert('error handling here');
                    }
                });
            });
        });
    </script>
    <div class="jumbotron col-lg-12">
        <form id="newpostform" action="newpost.action" method="POST" style="display: block;">
            <input type="hidden" id="userId" name="userId" value="${user.id}"/>
            <input type="hidden" id="wallId" name="wallId" value="${wall.id}"><s:property value="#parameters.wallId"/></input type="hidden">
            <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                <textarea id="content" name="content" placeholder="Tell something..."  class="form-control"></textarea>
                </div>
            </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="row">
                        <input type="submit" name="post-submit" id="post-submit" class="btn btn-sm btn-success col-sm-3 col-sm-offset-6" value="Post">
                        <input type="button" value="Clear" class="btn btn-sm col-sm-3"/>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/partitions/nmessage.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<s:set var="message" value="message"/>
<s:include value="message.jsp"/>

src/main/webapp/WEB-INF/jsp/partitions/npost.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<s:set var="post" value="post"/>
<s:include value="post.jsp"/>

src/main/webapp/WEB-INF/jsp/partitions/post.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<s:include value="postcontent.jsp"/>

src/main/webapp/WEB-INF/jsp/partitions/postcontent.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<div class="post panel blue">
    <s:hidden class="postId" value="%{#post.id}"/>
    <div class="header panel-heading">
        <s:set var="createdDate" value="#post.createdDate"/>
        <div class="row textright">
            <span class="col-sm-10">
                <s:property value="#post.createdBy.username"/>, <s:date name="createdDate" format="dd/MM/yyyy HH:mm"/>
            </span>
            <div class="col-sm-2">
                <button class="btn btn-sm btn-default" style="padding-bottom: 1px; padding-top: 1px;" onclick="removePost($(this).closest('.post'))">x</button>
            </div>
        </div>
    </div>
    <hr>
    <div class="content panel-body">
        <div class="row">
            <span class="col-sm-11">
                <s:property value="#post.content"/>
            </span>
        </div>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/partitions/sideMenu.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<div class="sideMenu list-group">
    <a href="myhome.action" class="list-group-item <s:if test="%{#active == 'home'}">active</s:if>">Home</a>
    <a href="myfriends.action" class="list-group-item <s:if test="%{#active == 'friends'}">active</s:if>">Friends</a>
    <s:if test="%{#active == 'friends' or #search == 'friends'}">
        <a href="findfriend.action"
           style="margin-left: 15px;"
           class="list-group-item <s:if test="%{#search == 'friends'}">active</s:if>">Find...<%--
        --%></a>
    </s:if>
    <a href="allchats.action" class="list-group-item <s:if test="%{#active == 'chats'}">active</s:if>">Messages</a>
    <a href="logout.action" class="list-group-item">Logout</a>
</div>

src/main/webapp/WEB-INF/jsp/partitions/wall.jsp
<%@ taglib prefix="s" uri="/struts-tags" %>
<div class="wall">
    <div class="row">
        <div class="col-lg-12">
            <s:include value="newpost.jsp"/>
        </div>
    </div>
    <div class="posts">
        <s:iterator value="%{#wall.posts}" var="post">
            <s:include value="post.jsp"/>
        </s:iterator>
    </div>
</div>